services:
  mysql:
    image: mysql:8.4
    container_name: assetpilot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: assetpilot
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2002"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: assetpilot-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: assetpilot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assetpilot?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2002
      SPRING_DATA_REDIS_HOST: redis
      SPRING_CACHE_TYPE: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started